apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 061039804626.dkr.ecr.ap-south-1.amazonaws.com/stu15-demo-frontend
  newName: 061039804626.dkr.ecr.ap-south-1.amazonaws.com/stu15-demo-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
