---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: stu15-eks-demo2
  region: ap-south-1
fargateProfiles:
  - name: frontend-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: frontend-fargate
