---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-flask-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-flask-backend
  template:
    metadata:
      labels:
        app: demo-flask-backend
    spec:
      containers:
        - name: demo-flask-backend
          image: 061039804626.dkr.ecr.ap-south-1.amazonaws.com/stu15-demo-flask-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
