---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-fargate
  template:
    metadata:
      labels:
        app: frontend-fargate
    spec:
      containers:
        - name: demo-frontend
          image: 061039804626.dkr.ecr.ap-south-1.amazonaws.com/stu15-demo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
